---
logging_network_name: logging_net

loki_container_name: loki
loki_port: 3100
loki_data_path: /home/reza/logging/loki

promtail_container_name: promtail
promtail_config_path: /home/reza/logging/promtail

