
logging_root_path: /opt/logging


logging_network_name: logging_network


loki_image: grafana/loki:latest
loki_container_name: loki
loki_port: 3100
loki_data_dir: /opt/loki


promtail_image: grafana/promtail:latest
promtail_container_name: promtail
promtail_port: 9080
promtail_config_path: /opt/promtail/promtail-config.yml


docker_log_path: /var/lib/docker/containers


ansible_user_id: "{{ ansible_user_id | default('root') }}"
ansible_user_gid: "{{ ansible_user_gid | default('root') }}"

