plpg_root_path: /opt/plpg

# Network
plpg_network_name: plpg_network

# Loki
loki_container_name: loki
loki_port: 3100
loki_data_dir: "{{ plpg_root_path }}/loki-data"

# Promtail
promtail_container_name: promtail
promtail_config_path: "{{ plpg_root_path }}/promtail/promtail-config.yml"
docker_log_path: /var/lib/docker/containers

# Prometheus
prometheus_container_name: prometheus
prometheus_port: 9090
prometheus_config_path: "{{ plpg_root_path }}/prometheus/prometheus.yml"
prometheus_data_dir: "{{ plpg_root_path }}/prometheus/data"

# Grafana
grafana_container_name: grafana
grafana_port: 3000
grafana_data_dir: "{{ plpg_root_path }}/grafana-data"

