---
# defaults file for logging
logging_network_name: logging_net
logging_compose_path: /opt/logging
logging_compose_template: docker-compose.logging.yml.j2
promtail_config_path: /etc/promtail
loki_data_path: /var/lib/loki
