version: "3.9"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:9.2.3
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data

  fluentd:
    build: ./fluentd
    container_name: fluentd
    depends_on:
      - elasticsearch
    ports:
      - "24224:24224"
    volumes:
      - ./fluentd/fluent.conf:/etc/fluentd/fluent.conf

  nginx:
    image: nginx:1.25
    container_name: nginx
    depends_on:
      - fluentd
    ports:
      - "8080:80"
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
        tag: nginx.access
    volumes:
      - nginx-logs:/var/log/nginx

  fluent-bit:
    image: fluent/fluent-bit:2.2
    container_name: fluent-bit
    depends_on:
      - fluentd
      - nginx
    volumes:
      - nginx-logs:/var/log/nginx:ro
      - ./fluent-bit/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
    command: ["fluent-bit", "-c", "/fluent-bit/etc/fluent-bit.conf"]



volumes:
  esdata:
  nginx-logs:
